//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedSeat
    {
        public int Id { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual Screening Screening { get; set; }
    }
}
